# Generated by Django 4.2 on 2023-05-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_post_categories_alter_post_time_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('PO', 'Политика'), ('SP', 'Спорт'), ('IT', 'ИТ'), ('SC', 'Наука'), ('SO', 'Общество')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2, verbose_name='Выбор'),
        ),
    ]
