# Generated by Django 4.2 on 2023-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_category_category_alter_post_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.IntegerField(default=1),
        ),
    ]
